// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonetLeiloesWeb.Data;

#nullable disable

namespace MonetLeiloesWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonetLeiloesWeb.Models.Leilao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("data_fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailUtilizador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("valor_base")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("emailUtilizador");

                    b.ToTable("Leiloes");
                });

            modelBuilder.Entity("MonetLeiloesWeb.Models.Licitacao", b =>
                {
                    b.Property<string>("emailUtilizador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("idLeilao")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("emailUtilizador", "idLeilao");

                    b.HasIndex("idLeilao");

                    b.ToTable("Licitacoes");
                });

            modelBuilder.Entity("MonetLeiloesWeb.Models.Morada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cod_postal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Moradas");
                });

            modelBuilder.Entity("MonetLeiloesWeb.Models.Quadro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("altura")
                        .HasColumnType("float");

                    b.Property<int>("ano")
                        .HasColumnType("int");

                    b.Property<string>("autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("fotografia")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("idLeilao")
                        .HasColumnType("int");

                    b.Property<double>("largura")
                        .HasColumnType("float");

                    b.Property<bool>("moldura")
                        .HasColumnType("bit");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("idLeilao");

                    b.ToTable("Quadros");
                });

            modelBuilder.Entity("MonetLeiloesWeb.Models.Utilizador", b =>
                {
                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("idMorada")
                        .HasColumnType("int");

                    b.Property<string>("nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("email");

                    b.HasIndex("idMorada");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("MonetLeiloesWeb.Models.Leilao", b =>
                {
                    b.HasOne("MonetLeiloesWeb.Models.Utilizador", "utilizador")
                        .WithMany()
                        .HasForeignKey("emailUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utilizador");
                });

            modelBuilder.Entity("MonetLeiloesWeb.Models.Licitacao", b =>
                {
                    b.HasOne("MonetLeiloesWeb.Models.Utilizador", "utilizador")
                        .WithMany()
                        .HasForeignKey("emailUtilizador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonetLeiloesWeb.Models.Leilao", "leilao")
                        .WithMany()
                        .HasForeignKey("idLeilao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("leilao");

                    b.Navigation("utilizador");
                });

            modelBuilder.Entity("MonetLeiloesWeb.Models.Quadro", b =>
                {
                    b.HasOne("MonetLeiloesWeb.Models.Leilao", "leilao")
                        .WithMany()
                        .HasForeignKey("idLeilao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("leilao");
                });

            modelBuilder.Entity("MonetLeiloesWeb.Models.Utilizador", b =>
                {
                    b.HasOne("MonetLeiloesWeb.Models.Morada", "morada")
                        .WithMany()
                        .HasForeignKey("idMorada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("morada");
                });
#pragma warning restore 612, 618
        }
    }
}
